export const SELECT_AGENT = 'SET_AGENT';
export const SELECT_ENVIRONMENT = 'SET_ENVIRONMENT';
export const SET_HYPERPARAMETER_RANGES = 'SET_HYPERPARAMETER_RANGES';
export const SET_EPISODES = 'SET_EPISODES';
export const SET_TRIALS = 'SET_TRIALS';
export const SET_SEARCH_TYPE = 'SET_SEARCH_TYPE';
export const SET_STEPS = 'SET_STEPS';
export const SET_SAMPLES = 'SET_SAMPLES';

export const STEP_BACKWARD = 'STEP_BACKWARD';
export const STEP_FORWARD = 'STEP_FORWARD';

export const BEGIN_SEARCH = 'BEGIN_SEARCH';
export const RECORD_TRIAL = 'RECORD_TRIAL';
export const RECORD_TRIAL_ERROR = 'RECORD_TRIAL_ERROR';
export const UNKNOWN_MESSAGE = 'UNKNOWN_MESSAGE';
