export const SELECT_AGENT = 'SET_AGENT';
export const SELECT_ENVIRONMENT = 'SET_ENVIRONMENT';
export const SET_HYPERPARAMETER = 'SET_HYPERPARAMETER';
export const SET_EPISODES = 'SET_EPISODES';
export const SET_TRIALS = 'SET_TRIALS';

export const STEP_BACKWARD = 'STEP_BACKWARD';
export const STEP_FORWARD = 'STEP_FORWARD';

export const RECORD_TRIAL = 'RECORD_TRIAL';
export const RECORD_TRIAL_ERROR = 'RECORD_TRIAL_ERROR';
export const UNKNOWN_MESSAGE = 'UNKNOWN_MESSAGE';

export const SET_ENVIRONMENT_STATE = 'SET_ENVIRONMENT_STATE';
export const START = 'START';
